----------------------------------------------------
CREATE TABLE DOCTOR (
  ID VARCHAR(15) PRIMARY KEY,
  NAME VARCHAR(100),
  AVAILABILITY CHAR(1)
);

CREATE TABLE CLINIC_ADMIN (
  ID VARCHAR(15) PRIMARY KEY,
  NAME VARCHAR(100)
);

CREATE TABLE PHARMACY (
  ID VARCHAR(15) PRIMARY KEY,
  NAME VARCHAR(100)
);

CREATE TABLE ROLE (
  ROLE_TYPE VARCHAR(5) PRIMARY KEY,
  ROLE_NAME VARCHAR(50)
);

CREATE TABLE USER_LOGIN (
  ID VARCHAR(15) PRIMARY KEY,
  USER_ID VARCHAR(15),
  USERNAME VARCHAR(30),
  PASSWORD VARCHAR(15),
  ROLE VARCHAR(5),
  CONSTRAINT FK_ROLE FOREIGN KEY (ROLE) REFERENCES role(role_type)
);

CREATE TABLE PATIENT (
  ID VARCHAR(15) PRIMARY KEY ,
  NAME VARCHAR(100),
  GENDER CHAR(1),
  ADDRESS VARCHAR(100),
  COMPLAINT VARCHAR(200),
  STATUS VARCHAR(15)
);

CREATE TABLE TREATMENT (
  ID VARCHAR(15) PRIMARY KEY,
  DOCTOR_ID VARCHAR(15),
  PATIENT_ID VARCHAR(15),
  CONSTRAINT FK_TREATMENT_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES doctor(id),
  CONSTRAINT FK_TREATMENT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES patient(id)
);

CREATE TABLE MEDICATION (
  ID VARCHAR(15) PRIMARY KEY,
  TREATMENT_ID VARCHAR(15),
  NOTES VARCHAR(200),
  ON_DUTY VARCHAR(15),
  CONSTRAINT FK_MEDIC_TREATMENT FOREIGN KEY (TREATMENT_ID) REFERENCES treatment(id),
  CONSTRAINT FK_MEDIC_ON_DUTY FOREIGN KEY (ON_DUTY) REFERENCES pharmacy(id)
);

CREATE TABLE MEDICINE (
  ID VARCHAR(15) PRIMARY KEY,
  NAME VARCHAR(50)
);

CREATE TABLE MEDICATION_DETAIL (
  ID VARCHAR(15) PRIMARY KEY,
  MEDICATION_ID VARCHAR(15),
  MEDICINE_ID VARCHAR(15),
  CONSTRAINT FK_MDTL_MEDICATION FOREIGN KEY (MEDICATION_ID) REFERENCES medication(id),
  CONSTRAINT FK_MDTL_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES medicine(id)
);